
package ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPaymentGateway", targetNamespace = "http://interfaces.core.sw.bps.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPaymentGateway {


    /**
     * 
     * @param terminalId
     * @param saleOrderId
     * @param userPassword
     * @param userName
     * @param saleReferenceId
     * @param orderId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpVerifyRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpVerifyRequest")
    @ResponseWrapper(localName = "bpVerifyRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpVerifyRequestResponse")
    public String bpVerifyRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId);

    /**
     * 
     * @param terminalId
     * @param userPassword
     * @param userName
     * @param refundOrderId
     * @param refundReferenceId
     * @param orderId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpRefundInquiryRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpRefundInquiryRequest")
    @ResponseWrapper(localName = "bpRefundInquiryRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpRefundInquiryRequestResponse")
    public String bpRefundInquiryRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "refundOrderId", targetNamespace = "")
        long refundOrderId,
        @WebParam(name = "refundReferenceId", targetNamespace = "")
        long refundReferenceId);

    /**
     * 
     * @param terminalId
     * @param userPassword
     * @param userName
     * @param refundOrderId
     * @param refundReferenceId
     * @param orderId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpRefundVerifyRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpRefundVerifyRequest")
    @ResponseWrapper(localName = "bpRefundVerifyRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpRefundVerifyRequestResponse")
    public String bpRefundVerifyRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "refundOrderId", targetNamespace = "")
        long refundOrderId,
        @WebParam(name = "refundReferenceId", targetNamespace = "")
        long refundReferenceId);

    /**
     * 
     * @param terminalId
     * @param saleOrderId
     * @param userPassword
     * @param userName
     * @param saleReferenceId
     * @param orderId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpSettleRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpSettleRequest")
    @ResponseWrapper(localName = "bpSettleRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpSettleRequestResponse")
    public String bpSettleRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId);

    /**
     * 
     * @param amount
     * @param terminalId
     * @param userPassword
     * @param payerId
     * @param userName
     * @param localTime
     * @param localDate
     * @param additionalData
     * @param subServiceId
     * @param orderId
     * @param callBackUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpDynamicPayRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpDynamicPayRequest")
    @ResponseWrapper(localName = "bpDynamicPayRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpDynamicPayRequestResponse")
    public String bpDynamicPayRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "amount", targetNamespace = "")
        long amount,
        @WebParam(name = "localDate", targetNamespace = "")
        String localDate,
        @WebParam(name = "localTime", targetNamespace = "")
        String localTime,
        @WebParam(name = "additionalData", targetNamespace = "")
        String additionalData,
        @WebParam(name = "callBackUrl", targetNamespace = "")
        String callBackUrl,
        @WebParam(name = "payerId", targetNamespace = "")
        long payerId,
        @WebParam(name = "subServiceId", targetNamespace = "")
        long subServiceId);

    /**
     * 
     * @param amount
     * @param terminalId
     * @param userPassword
     * @param userName
     * @param localTime
     * @param localDate
     * @param additionalData
     * @param orderId
     * @param callBackUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpCumulativeDynamicPayRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpCumulativeDynamicPayRequest")
    @ResponseWrapper(localName = "bpCumulativeDynamicPayRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpCumulativeDynamicPayRequestResponse")
    public String bpCumulativeDynamicPayRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "amount", targetNamespace = "")
        long amount,
        @WebParam(name = "localDate", targetNamespace = "")
        String localDate,
        @WebParam(name = "localTime", targetNamespace = "")
        String localTime,
        @WebParam(name = "additionalData", targetNamespace = "")
        String additionalData,
        @WebParam(name = "callBackUrl", targetNamespace = "")
        String callBackUrl);

    /**
     * 
     * @param terminalId
     * @param saleOrderId
     * @param userPassword
     * @param userName
     * @param saleReferenceId
     * @param orderId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpReversalRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpReversalRequest")
    @ResponseWrapper(localName = "bpReversalRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpReversalRequestResponse")
    public String bpReversalRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId);

    /**
     * 
     * @param amount
     * @param terminalId
     * @param userPassword
     * @param payerId
     * @param userName
     * @param localTime
     * @param localDate
     * @param additionalData
     * @param orderId
     * @param callBackUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpPayRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpPayRequest")
    @ResponseWrapper(localName = "bpPayRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpPayRequestResponse")
    public String bpPayRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "amount", targetNamespace = "")
        long amount,
        @WebParam(name = "localDate", targetNamespace = "")
        String localDate,
        @WebParam(name = "localTime", targetNamespace = "")
        String localTime,
        @WebParam(name = "additionalData", targetNamespace = "")
        String additionalData,
        @WebParam(name = "callBackUrl", targetNamespace = "")
        String callBackUrl,
        @WebParam(name = "payerId", targetNamespace = "")
        long payerId);

    /**
     * 
     * @param terminalId
     * @param saleOrderId
     * @param userPassword
     * @param userName
     * @param orderId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpSaleReferenceIdRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpSaleReferenceIdRequest")
    @ResponseWrapper(localName = "bpSaleReferenceIdRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpSaleReferenceIdRequestResponse")
    public String bpSaleReferenceIdRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId);

    /**
     * 
     * @param amount
     * @param terminalId
     * @param userPassword
     * @param payerId
     * @param userName
     * @param localTime
     * @param localDate
     * @param additionalData
     * @param orderId
     * @param callBackUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpChargePayRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpChargePayRequest")
    @ResponseWrapper(localName = "bpChargePayRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpChargePayRequestResponse")
    public String bpChargePayRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "amount", targetNamespace = "")
        long amount,
        @WebParam(name = "localDate", targetNamespace = "")
        String localDate,
        @WebParam(name = "localTime", targetNamespace = "")
        String localTime,
        @WebParam(name = "additionalData", targetNamespace = "")
        String additionalData,
        @WebParam(name = "callBackUrl", targetNamespace = "")
        String callBackUrl,
        @WebParam(name = "payerId", targetNamespace = "")
        long payerId);

    /**
     * 
     * @param terminalId
     * @param saleOrderId
     * @param userPassword
     * @param userName
     * @param saleReferenceId
     * @param orderId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpInquiryRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpInquiryRequest")
    @ResponseWrapper(localName = "bpInquiryRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpInquiryRequestResponse")
    public String bpInquiryRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId);

    /**
     * 
     * @param terminalId
     * @param refundAmount
     * @param saleOrderId
     * @param userPassword
     * @param userName
     * @param saleReferenceId
     * @param orderId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bpRefundRequest", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpRefundRequest")
    @ResponseWrapper(localName = "bpRefundRequestResponse", targetNamespace = "http://interfaces.core.sw.bps.com/", className = "ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat.BpRefundRequestResponse")
    public String bpRefundRequest(
        @WebParam(name = "terminalId", targetNamespace = "")
        long terminalId,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword,
        @WebParam(name = "orderId", targetNamespace = "")
        long orderId,
        @WebParam(name = "saleOrderId", targetNamespace = "")
        long saleOrderId,
        @WebParam(name = "saleReferenceId", targetNamespace = "")
        long saleReferenceId,
        @WebParam(name = "refundAmount", targetNamespace = "")
        long refundAmount);

}
