
package ir.jnf.maven.libs.Kernel.soapClients.paymentGateway.mellat;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentGatewayImplService", targetNamespace = "http://service.pgw.sw.bps.com/", wsdlLocation = "https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl")
public class PaymentGatewayImplService
    extends Service
{

    private final static URL PAYMENTGATEWAYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTGATEWAYIMPLSERVICE_EXCEPTION;
    private final static QName PAYMENTGATEWAYIMPLSERVICE_QNAME = new QName("http://service.pgw.sw.bps.com/", "PaymentGatewayImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTGATEWAYIMPLSERVICE_WSDL_LOCATION = url;
        PAYMENTGATEWAYIMPLSERVICE_EXCEPTION = e;
    }

    public PaymentGatewayImplService() {
        super(__getWsdlLocation(), PAYMENTGATEWAYIMPLSERVICE_QNAME);
    }

    public PaymentGatewayImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTGATEWAYIMPLSERVICE_QNAME, features);
    }

    public PaymentGatewayImplService(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTGATEWAYIMPLSERVICE_QNAME);
    }

    public PaymentGatewayImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTGATEWAYIMPLSERVICE_QNAME, features);
    }

    public PaymentGatewayImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentGatewayImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPaymentGateway
     */
    @WebEndpoint(name = "PaymentGatewayImplPort")
    public IPaymentGateway getPaymentGatewayImplPort() {
        return super.getPort(new QName("http://service.pgw.sw.bps.com/", "PaymentGatewayImplPort"), IPaymentGateway.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPaymentGateway
     */
    @WebEndpoint(name = "PaymentGatewayImplPort")
    public IPaymentGateway getPaymentGatewayImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.pgw.sw.bps.com/", "PaymentGatewayImplPort"), IPaymentGateway.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTGATEWAYIMPLSERVICE_EXCEPTION!= null) {
            throw PAYMENTGATEWAYIMPLSERVICE_EXCEPTION;
        }
        return PAYMENTGATEWAYIMPLSERVICE_WSDL_LOCATION;
    }

}
