package jsfui;

public enum Area{
	
AJO("آجودانیه"),
AZA("آذربایجان"),
AZARI("آذری"),
ARARAT("آرارات"),
ARJANTIN("آرژانتین"),
AZADSHAR("آزاد شهر"),
AHANG("آهنگ"),
EBRAHIMABAD("ابراهیم‌آباد"),
ABOZAR("ابوذر"),
EHTESHAMIEH("احتشامیه"),
EKHTIYARIEH("اختیاریه"),
ARAMANEH("ارامنه"),
ERAM("ارم"),
AZGOL("ازگل"),
OSTADMOEIN("استاد معین"),
ESTAKHR("استخر"),
ESFANDIYARI("اسفندیاری"),
ESKANDARI("اسکندری"),
ESLAMABAD("اسلام‌‌آباد"),
AFSARIEH("افسریه"),
AGHDASIEH("اقدسیه"),
EKBATAN("اکباتان"),
ALMAHDI("المهدی"),
ELAHIEH("الهیه"),
EMAMHOSEIN("امام حسین"),
EMAMZADEHGHASEM("امامزاده قاسم"),
AMANIEYH("امانیه"),
AMIRBAHADOR("امیر بهادر"),
AMIRABAD("امیرآباد"),
AMIRIEH("امیریه"),
ANDISHE("اندیشه"),
OGHAF("اوقاف"),
EVIN("اوین"),
IRANSHAR("ایرانشهر"),
BAZAR("بازار"),
BAGHEAZARI("باغ آذری"),
BAGHEREZVAN("باغ رضوان"),
BAGHERKHAN("باقرخان"),
BERYANAK("بریانک"),
BOLVARKESHAVARZ("بلوار کشاورز"),
BOSTANVELAYAT("بوستان ولایت"),
BOMEHEN("بومهن"),
BAHARAN("بهاران"),
BAHARESTAN("بهارستان"),
BEHJATABAD("بهجت‌آباد"),
BAHMANYAR("بهمن‌ یار"),
PARKEAZADEGAN("پارک آزادگان"),
PARKESHAR("پارک شهر"),
PARKELALEH("پارک لاله"),
PASDARAN("پاسداران"),
PAKDASHT("پاکدشت"),
PAMENAR("پامنار"),
PARDIS("پردیس"),
PARDISAN("پردیسان"),
PARAND("پرند"),
POLEROMI("پل رومی"),
PONAK("پونک"),
PIROZI("پیروزی"),
PEYKANSHAR("پیکان شهر"),
TAJRISH("تجریش"),
TOHID("توحید"),
TEHRANSAR("تهران‌سر"),
TEHRANNO("تهران‌نو"),
TEHRANVILA("تهران‌ویلا"),
TEHRANPSH("تهرانپارس شرقی"),
TEHPAGH("تهرانپارس غربی"),
JORDAN("جردن"),
JAMARAN("جماران"),
JAMALZA("جمال‌زاده"),
JAMSHID("جمشیدیه"),
JOMHORI("جمهوری"),
JANATMA("جنت‌‌آباد مرکزی"),
JANATJO("جنت‌آباد جنوبی"),
JANATSH("جنت‌آباد شمالی"),
JAVADIEH("جوادیه"),
JAVANMARDGHASAB("جوانمرد قصاب"),
JEY("جی"),
JEYHON("جیحون"),
CHARSADDASTGAH("چهارصد دستگاه"),
CHITGAR("چیتگر"),
CHITSHOMA("چیتگر شمالی"),
CHIZAR("چیذر"),
HASANABA("حسن‌آباد"),
HASANABADBAGHERFAR("حسن‌آباد باقرفر"),
HASANSH("حسن‌آباد شمالی"),
HESHMATIEH("حشمتیه"),
HAKIMIEH("حکیمیه"),
KHANIABAD("خانی‌آباد"),
KHAZANEH("خزانه"),
KHALIJFARS("خلیج فارس"),
KHORIN("خورین"),
DARABAD("دارآباد"),
DANESHGAHTEHRAN("دانشگاه تهران"),
DABESTAN("دبستان"),
DARBAND("دربند"),
DARDASHT("دردشت"),
DARAKEH("درکه"),
DARVAZEHSHEMIRAN("دروازه شمیران"),
DAROS("دروس"),
DARYANO("دریان‌نو‍"),
DEZASHIB("دزاشیب"),
DOLAB("دولاب"),
DOLATABAD("دولت‌آباد"),
DEHVANAK("ده‌ونک"),
DEHKADEHOLAMPIK("دهکده المپیک"),
DEYLAMANJONOBI("دیلمان جنوبی"),
ROBATKARIM("رباط کریم"),
RODEHEN("رودهن"),
ZARGANDEH("زرگنده"),
ZAFERANIEH("زعفرانیه"),
ZEHTABI("زهتابی"),
ZEYNABIEH("زینبیه"),
SAZMANEAB("سازمان آب"),
SAZMANEBARNAME("سازمان برنامه"),
SATARKHAN("ستارخان"),
SARSABZ("سرسبز"),
SAADATABAD("سعادت‌آباد"),
SAADABAD("سعدآباد"),
SALSABIL("سلسبیل"),
SOLEYMANIEH("سلیمانیه"),
SANGELAJ("سنگلج"),
SOHANAK("سوهانک"),
SOHRJO("سهروردی جنوبی"),
SOHRSHO("سهروردی شمالی"),
SEYEDKHAN("سید خندان"),
SHAPOR("شاپور"),
SHADABD("شادآباد"),
SHADEMAN("شادمان"),
SHAHIN("شاهین"),
SHARIFABAD("شریف‌آباد"),
SHOKOFEH("شکوفه"),
SHAMSABAD("شمس‌آباد"),
SHEMIRANNO("شمیران‌نو"),
SHOSH("شوش"),
SHARREY("شهر ری"),
SHARZIBA("شهر زیبا"),
SHAREQODS("شهر قدس"),
SHRARA("شهرآرا"),
SHARANJONOBI("شهران جنوبی"),
SHARANSHO("شهران شمالی"),
SHARAKAPADANA("شهرک آپادانا"),
SHRAAKAZADI("شهرک آزادی"),
SHARAKEASEMAN("شهرک آسمان"),
SHARAKEABOZAR("شهرک ابوذر"),
SHRAKEARGHAVAN("شهرک ارغوان"),
SHARAKESTEGHLAL("شهرک استقلال"),
SHARAKEKHOMENI("شهرک امام خمینی"),
SHARAKEOMID("شهرک امید"),
SHARAKEAMIRAL("شهرک امیرالمومنین"),
SHARAKEANSRA("شهرک انصار"),
SHARAKEBOKHARAEI("شهرک بخارایی"),
SHARAKEBESAT("شهرک بعثت"),
SHARAKEPARS("شهرک پارس"),
SHARAKEPASDARN("شهرک پاسداران"),
SHARAKEPARVAZ("شهرک پرواز"),
SHARAKETAKHTI("شهرک تختی"),
SHARAKECHESHMEH("شهرک چشمه"),
SHARAKEDANESHGAH("شهرک دانشگاه"),
SHARAKEDARYA("شهرک دریا"),
SHARAKEREZVAN("شهرک رضوان"),
SHARAKERAZAVIEH("شهرک رضویه"),
SHARAKEJANDARMERI("شهرک ژاندارمری"),
SHARAKESHAHIN("شهرک شاهین"),
SHARAKESHRIATI("شهرک شریعتی"),
SHARAKESHARIFI("شهرک شریفی"),
SHARAKESHARBANI("شهرک شهربانی"),
SHARAKESHARDARI("شهرک شهرداری"),
SHARAKESHAHIDMOFATEH("شهرک شهید مفتح"),
SHARAKETALEGANI("شهرک طالقانی"),
SHARAKEABASPOOR("شهرک عباسپور"),
SHARAKEABASI("شهرک عباسی"),
SHARAKEGHARB("شهرک غرب"),
SHARAKEGHAZALI("شهرک غزالی"),
SHARAKEFATEME("شهرک فاطمه الزهرا"),
SHARAKEFERDOS("شهرک فردوس"),
SHARAKEFARHANGIYAN("شهرک فرهنگیان"),
SHARAKEFARHANGIANGHARB("شهرک فرهنگیان غرب"),
SHARAKEQODS("شهرک قدس"),
SHARAKKAZEMIEH("شهرک کاظمیه"),
SHARAKKAMALI("شهرک کمالی"),
SHRAKKOHSAR("شهرک کوهسار"),
SHARAKKIANSHAR("شهرک کیانشهر"),
SHARAKGOLESTAN("شهرک گلستان"),
SHARAKEGOLESTANGHARBI("شهرک گلستان غربی"),
SHARAKEGOLHA("شهرک گلها"),
SHARAKEMAHALATI("شهرک محلاتی"),
SHARAKEMOSLEMIN("شهرک مسلمین"),
SHARAKENAFT("شهرک نفت"),
SHARAKEVALFAJR("شهرک والفجر"),
SHARAKVALIASR("شهرک ولیعصر"),
SHARAKEVILASHAR("شهرک ویلاشهر"),
SHARAKEHEJRAT("شهرک هجرت"),
SHARIYAR("شهریار"),
SHIAYAN("شیان"),
SHEYKHRAIIS("شیخ الرئیس"),
SHEYALHADI("شیخ هادی"),
SHIRAZI("شیرازی"),
SADEGHIE("صادقیه"),
SADDASTGAH("صد دستگاه"),
ZARABKHANE("ضرابخانه"),
TALEGHANI("طالقانی"),
TARASHT("طرشت"),
ZAFAR("ظفر"),
ZAHITABAD("ظهیرآباد"),
ABASABAD("عباس‌آباد"),
ABDOLAB("عبدل‌آباد"),
ESHRATABAD("عشرت‌آباد"),
ELMOSANAT("علم و صنعت"),
ALIABAADJONOBI("علی‌آباد جنوبی"),
ALIABADSHOMALI("علی‌آباد شمالی"),
FATEMI("فاطمی"),
FADAK("فدک"),
FARAJABAD("فرح‌آباد"),
FARAHZAD("فرحزاد"),
FARMANIEH("فرمانیه"),
FORODGAHMEHRABAD("فرودگاه مهر‌آباد"),
FASHAM("فشم"),
FALAH("فلاح"),
FIROZKOH("فیروزکوه"),
GHARCHAK("قرچک"),
GHEZELGHALYE("قزل قلعه"),
GHASR("قصر"),
GHASRF1("قصر فیروزه ۱"),
GHASREF2("قصر فیروزه ۲"),
GHALFATAB("قلعه فتح‌آباد"),
GHOLHAK("قلهک"),
GHANATKOSAR("قنات‌کوثر"),
GHYAMDASHT("قیامدشت"),
GHEYTARIEH("قیطریه"),
KAREVAN("کاروان"),
KASHANAK("کاشانک"),
KAZEMABAD("کاظم‌آباد"),
KALAD("کالاد"),
KAMRANIEH("کامرانیه"),
KETABKH("کتابخانه ملی ایران"),
KARIMABAD("کریم‌آباد"),
KAN("کن"),
KOHAK("کوهک"),
KOYESLAM("کوی اسلام"),
KOYEBIMEH("کوی بیمه"),
KOYEDANSHGAH("کوی دانشگاه"),
KOFERDOS("کوی فردوس"),
KOMEHRABAD("کوی مهرآباد"),
KO17SH("کوی هفدهم شهریور"),
GANDI("گاندی"),
GOLAB("گلاب دره"),
GOMROK("گمرک"),
GISHA("گیشا "),
LAVASAN("لواسان"),
LAVIZAN("لویزان"),
MOBARAKABAD("مبارک‌آباد"),
MOBARAKABADBEHESHTI("مبارک‌آباد بهشتی"),
VARZRSHGAHAZADI("مجموعه ورزشگاه آزادی"),
MAJIDABAD("مجید‌آباد"),
MAJIDIEH("مجیدیه"),
MAHMODIEH("محمودیه"),
MORADABAD("مرادآباد"),
MARZDARAN("مرزداران"),
MASYOIEIDEH("مسعودیه"),
MOSHIRE("مشیریه"),
MOTAHARI("مطهری"),
MALEKABAD("ملک‌آباد"),
MANSORIEH("منصوریه"),
MANZARIEH("منظریه"),
MONIERIEH("منیریه"),
MOLAVI("مولوی"),
MEHRABADJONOBI("مهرآباد جنوبی"),
MEHRAN("مهران"),
MEYDANEAZADI("میدان آزادی"),
MEYDANENGHELAB("میدان انقلاب"),
MEYDANEHOR("میدان حر"),
MEYDANEVALIASR("میدان ولیعصر"),
MIRDAMAD("میرداماد"),
NARMAK("نارمک"),
NAZIABAD("نازی‌آباد"),
NEZAMABAD("نظام‌آباد"),
NEMATABAD("نعمت‌آباد"),
NAVAB("نواب"),
NIAVARAN("نیاوران"),
NIROHAVAEI("نیرو هوایی"),
VAHIDIEH("وحیدیه"),
VARAMIN("ورامین"),
VARDAVARD("وردآورد"),
VASFNARD("وصفنارد"),
VELENJAK("ولنجک"),
VANAK("ونک"),
HASHEMABAD("هاشم‌آباد"),
HAFTHOZ("هفت‌ حوض"),
YAKHCHIABAD("ياخچی‌آباد"),
YAFTABAD("يافت‌آباد"),
USEFABAD("یوسف‌آباد");
	
	private String areaName;

	private Area(String areaName) {
		this.areaName = areaName;
	}

	public String getAreaName() {
		return areaName;
	}

}